
export const UPDATE_MOVIE_LIST = 'UPDATE_MOVIE_LIST';
export const INSERT_TO_RATING_LIST = 'INSERT_TO_RATING_LIST';
export const UPDATE_RATING_LIST = 'UPDATE_RATING_LIST';
export const UPDATE_FAV_MOVIE_LIST = 'UPDATE_FAV_MOVIE_LIST';
export const UPDATE_FILTERED_FAV_MOVIE_LIST = 'UPDATE_FILTERED_FAV_MOVIE_LIST';