 export const HOME_SCREEN = {
    MOVIE_SCREEN : 'Movies',
    MOVIE_SCREEN_PAGE : 'MOVIE_SCREEN_PAGE',
    FAVOURITE_MOVIE_SCREEN : 'Favourits',
    FAVOURITE_MOVIE_SCREEN_PAGE : 'FAVOURITE_MOVIE_SCREEN_PAGE',
    DETAILS_PAGE : 'DETAILS_PAGE',
    MAIN_TABS : 'MAIN_TABS'
  };
  